# server
server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie

spring:
  # MyBatis
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@//${DATABASE_URL}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
  # Thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    check-template-location: true
